//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL_WPF_Garlic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vpostinfo
    {
        public int p_id { get; set; }
        public string pi_user { get; set; }
        public Nullable<long> pi_votes { get; set; }
        public Nullable<long> pi_comments { get; set; }
    }
}
