-- MySQL Script generated by MySQL Workbench
-- 02/27/16 14:28:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`u_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`u_users` (
  `u_username` VARCHAR(20) NOT NULL COMMENT '',
  `u_email` VARCHAR(50) NOT NULL COMMENT '',
  `u_password` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`u_username`)  COMMENT '',
  UNIQUE INDEX `u_username_UNIQUE` (`u_username` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`p_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`p_posts` (
  `p_id` INT NOT NULL COMMENT '',
  `p_content` VARCHAR(10000) NOT NULL COMMENT '',
  `p_date` DATETIME NOT NULL COMMENT '',
  `p_u_username` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`p_id`)  COMMENT '',
  INDEX `fk_p_posts_u_users_idx` (`p_u_username` ASC)  COMMENT '',
  CONSTRAINT `fk_p_posts_u_users`
    FOREIGN KEY (`p_u_username`)
    REFERENCES `mydb`.`u_users` (`u_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`co_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`co_comments` (
  `co_p_id` INT NOT NULL COMMENT '',
  `co_p_commentof` INT NOT NULL COMMENT '',
  PRIMARY KEY (`co_p_id`)  COMMENT '',
  INDEX `fk_co_comments_p_posts2_idx` (`co_p_commentof` ASC)  COMMENT '',
  CONSTRAINT `fk_co_comments_p_posts1`
    FOREIGN KEY (`co_p_id`)
    REFERENCES `mydb`.`p_posts` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_co_comments_p_posts2`
    FOREIGN KEY (`co_p_commentof`)
    REFERENCES `mydb`.`p_posts` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`c_cloves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`c_cloves` (
  `c_name` VARCHAR(50) NOT NULL COMMENT '',
  `c_access` TINYINT(1) NOT NULL COMMENT '',
  `c_description` VARCHAR(1000) NULL COMMENT '',
  PRIMARY KEY (`c_name`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sm_socialmedias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sm_socialmedias` (
  `sm_name` VARCHAR(20) NOT NULL COMMENT '',
  `sm_username` VARCHAR(50) NOT NULL COMMENT '',
  `sm_email` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`sm_name`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`r_rankings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`r_rankings` (
  `r_rank` INT NOT NULL COMMENT '',
  `r_context` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`r_rank`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`v_votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`v_votes` (
  `v_upvote` TINYINT(1) NOT NULL COMMENT '',
  `v_date` DATETIME NOT NULL COMMENT '',
  `v_p_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`v_date`, `v_p_id`)  COMMENT '',
  INDEX `fk_v_votes_p_posts1_idx` (`v_p_id` ASC)  COMMENT '',
  CONSTRAINT `fk_v_votes_p_posts1`
    FOREIGN KEY (`v_p_id`)
    REFERENCES `mydb`.`p_posts` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`a_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`a_articles` (
  `a_p_id` INT NOT NULL COMMENT '',
  `a_c_clove` VARCHAR(50) NOT NULL COMMENT '',
  `a_title` VARCHAR(200) NOT NULL COMMENT '',
  `a_r_rank` INT NOT NULL COMMENT '',
  PRIMARY KEY (`a_p_id`, `a_c_clove`, `a_r_rank`)  COMMENT '',
  INDEX `fk_a_articles_c_cloves1_idx` (`a_c_clove` ASC)  COMMENT '',
  INDEX `fk_a_articles_r_rankings1_idx` (`a_r_rank` ASC)  COMMENT '',
  CONSTRAINT `fk_a_articles_p_posts1`
    FOREIGN KEY (`a_p_id`)
    REFERENCES `mydb`.`p_posts` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_a_articles_c_cloves1`
    FOREIGN KEY (`a_c_clove`)
    REFERENCES `mydb`.`c_cloves` (`c_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_a_articles_r_rankings1`
    FOREIGN KEY (`a_r_rank`)
    REFERENCES `mydb`.`r_rankings` (`r_rank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`csm_connectedsocialmedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`csm_connectedsocialmedia` (
  `csm_u_username` VARCHAR(20) NOT NULL COMMENT '',
  `csm_sm_name` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`csm_u_username`, `csm_sm_name`)  COMMENT '',
  INDEX `fk_u_users_has_sm_socialmedias_sm_socialmedias1_idx` (`csm_sm_name` ASC)  COMMENT '',
  INDEX `fk_u_users_has_sm_socialmedias_u_users1_idx` (`csm_u_username` ASC)  COMMENT '',
  CONSTRAINT `fk_u_users_has_sm_socialmedias_u_users1`
    FOREIGN KEY (`csm_u_username`)
    REFERENCES `mydb`.`u_users` (`u_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_u_users_has_sm_socialmedias_sm_socialmedias1`
    FOREIGN KEY (`csm_sm_name`)
    REFERENCES `mydb`.`sm_socialmedias` (`sm_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`s_subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`s_subscription` (
  `s_u_username` VARCHAR(20) NOT NULL COMMENT '',
  `s_c_clovename` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`s_u_username`, `s_c_clovename`)  COMMENT '',
  INDEX `fk_u_users_has_c_cloves_c_cloves1_idx` (`s_c_clovename` ASC)  COMMENT '',
  INDEX `fk_u_users_has_c_cloves_u_users1_idx` (`s_u_username` ASC)  COMMENT '',
  CONSTRAINT `fk_u_users_has_c_cloves_u_users1`
    FOREIGN KEY (`s_u_username`)
    REFERENCES `mydb`.`u_users` (`u_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_u_users_has_c_cloves_c_cloves1`
    FOREIGN KEY (`s_c_clovename`)
    REFERENCES `mydb`.`c_cloves` (`c_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ad_admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ad_admins` (
  `ad_u_username` VARCHAR(20) NOT NULL COMMENT '',
  `ad_c_clovename` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`ad_u_username`, `ad_c_clovename`)  COMMENT '',
  INDEX `fk_u_users_has_c_cloves_c_cloves2_idx` (`ad_c_clovename` ASC)  COMMENT '',
  INDEX `fk_u_users_has_c_cloves_u_users2_idx` (`ad_u_username` ASC)  COMMENT '',
  UNIQUE INDEX `ad_u_username_UNIQUE` (`ad_u_username` ASC)  COMMENT '',
  UNIQUE INDEX `c_cloves_c_name_UNIQUE` (`ad_c_clovename` ASC)  COMMENT '',
  CONSTRAINT `fk_u_users_has_c_cloves_u_users2`
    FOREIGN KEY (`ad_u_username`)
    REFERENCES `mydb`.`u_users` (`u_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_u_users_has_c_cloves_c_cloves2`
    FOREIGN KEY (`ad_c_clovename`)
    REFERENCES `mydb`.`c_cloves` (`c_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`re_realtedcloves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`re_realtedcloves` (
  `re_c_clovename1` VARCHAR(50) NOT NULL COMMENT '',
  `re_c_clovename2` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`re_c_clovename1`, `re_c_clovename2`)  COMMENT '',
  INDEX `fk_c_cloves_has_c_cloves_c_cloves2_idx` (`re_c_clovename2` ASC)  COMMENT '',
  INDEX `fk_c_cloves_has_c_cloves_c_cloves1_idx` (`re_c_clovename1` ASC)  COMMENT '',
  CONSTRAINT `fk_c_cloves_has_c_cloves_c_cloves1`
    FOREIGN KEY (`re_c_clovename1`)
    REFERENCES `mydb`.`c_cloves` (`c_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_c_cloves_has_c_cloves_c_cloves2`
    FOREIGN KEY (`re_c_clovename2`)
    REFERENCES `mydb`.`c_cloves` (`c_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
