//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garlic_WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_votes
    {
        public int v_p_post { get; set; }
        public bool v_upvote { get; set; }
        public System.DateTime v_date { get; set; }
    
        public virtual p_posts p_posts { get; set; }
    }
}
