//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garlic_WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vcloveinfo
    {
        public int ci_cloveID { get; set; }
        public string ci_cloveName { get; set; }
        public Nullable<long> ci_subscribers { get; set; }
        public Nullable<long> ci_admins { get; set; }
        public Nullable<long> ci_articles { get; set; }
    }
}
