//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garlic_WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vclovearticles
    {
        public int a_p_id { get; set; }
        public string a_title { get; set; }
        public Nullable<int> a_c_clove { get; set; }
        public string p_u_username { get; set; }
        public string cloveName { get; set; }
        public Nullable<int> isPublic { get; set; }
        public string cloveDesc { get; set; }
        public Nullable<long> commentCount { get; set; }
        public Nullable<long> voteCount { get; set; }
    }
}
