//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garlic_WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vpostinfo
    {
        public int pi_postID { get; set; }
        public System.DateTime pi_postDate { get; set; }
        public string pi_postContent { get; set; }
        public string pi_user { get; set; }
        public Nullable<long> pi_votes { get; set; }
        public Nullable<long> pi_comments { get; set; }
        public string pi_postTitle { get; set; }
    }
}
