//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garlic_WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vuservotes
    {
        public string uu_user { get; set; }
        public Nullable<long> uu_articles_votes { get; set; }
        public Nullable<long> uu_comments_votes { get; set; }
        public Nullable<long> uu_total_votes { get; set; }
    }
}
