//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garlic_WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vuserrankings
    {
        public string u_username { get; set; }
        public Nullable<long> ur_superhot { get; set; }
        public Nullable<long> ur_hot { get; set; }
        public Nullable<long> ur_rising { get; set; }
        public Nullable<long> ur_upcoming { get; set; }
        public Nullable<long> ur_total { get; set; }
    }
}
