-- MySQL Script generated by MySQL Workbench
-- 03/15/16 21:55:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema garlic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `garlic` ;

-- -----------------------------------------------------
-- Schema garlic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `garlic` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `garlic` ;

-- -----------------------------------------------------
-- Table `garlic`.`u_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`u_users` ;

CREATE TABLE IF NOT EXISTS `garlic`.`u_users` (
  `u_username` VARCHAR(20) NOT NULL COMMENT '',
  `u_password` VARCHAR(100) NOT NULL COMMENT '',
  `u_email` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`u_username`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`p_posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`p_posts` ;

CREATE TABLE IF NOT EXISTS `garlic`.`p_posts` (
  `p_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `p_content` VARCHAR(10000) NOT NULL COMMENT '',
  `p_date` DATETIME NOT NULL COMMENT '',
  `p_u_username` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`p_id`)  COMMENT '',
  INDEX `fk_p_posts_u_users_idx` (`p_u_username` ASC)  COMMENT '',
  CONSTRAINT `fk_p_posts_u_users`
    FOREIGN KEY (`p_u_username`)
    REFERENCES `garlic`.`u_users` (`u_username`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`r_rankings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`r_rankings` ;

CREATE TABLE IF NOT EXISTS `garlic`.`r_rankings` (
  `r_rank` INT NOT NULL COMMENT '',
  `r_context` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`r_rank`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`c_clove`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`c_clove` ;

CREATE TABLE IF NOT EXISTS `garlic`.`c_clove` (
  `c_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `c_name` VARCHAR(50) NOT NULL COMMENT '',
  `c_access` TINYINT(1) NOT NULL COMMENT '',
  `c_description` VARCHAR(1000) NULL COMMENT '',
  PRIMARY KEY (`c_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`a_articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`a_articles` ;

CREATE TABLE IF NOT EXISTS `garlic`.`a_articles` (
  `a_p_id` INT NOT NULL COMMENT '',
  `a_title` VARCHAR(200) NOT NULL COMMENT '',
  `a_r_rank` INT NULL COMMENT '',
  `a_c_clove` INT NULL COMMENT '',
  PRIMARY KEY (`a_p_id`)  COMMENT '',
  INDEX `fk_a_articles_r_rankings1_idx` (`a_r_rank` ASC)  COMMENT '',
  INDEX `fk_a_articles_c_clove1_idx` (`a_c_clove` ASC)  COMMENT '',
  CONSTRAINT `fk_a_articles_p_posts1`
    FOREIGN KEY (`a_p_id`)
    REFERENCES `garlic`.`p_posts` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_a_articles_r_rankings1`
    FOREIGN KEY (`a_r_rank`)
    REFERENCES `garlic`.`r_rankings` (`r_rank`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_a_articles_c_clove1`
    FOREIGN KEY (`a_c_clove`)
    REFERENCES `garlic`.`c_clove` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`c_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`c_comments` ;

CREATE TABLE IF NOT EXISTS `garlic`.`c_comments` (
  `c_p_id` INT NOT NULL COMMENT '',
  `c_p_commentOf` INT NOT NULL COMMENT '',
  PRIMARY KEY (`c_p_id`)  COMMENT '',
  INDEX `fk_c_comments_p_posts2_idx` (`c_p_commentOf` ASC)  COMMENT '',
  CONSTRAINT `fk_c_comments_p_posts1`
    FOREIGN KEY (`c_p_id`)
    REFERENCES `garlic`.`p_posts` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_c_comments_p_posts2`
    FOREIGN KEY (`c_p_commentOf`)
    REFERENCES `garlic`.`p_posts` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`sm_socialmedias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`sm_socialmedias` ;

CREATE TABLE IF NOT EXISTS `garlic`.`sm_socialmedias` (
  `sm_name` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`sm_name`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`v_votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`v_votes` ;

CREATE TABLE IF NOT EXISTS `garlic`.`v_votes` (
  `v_date` DATETIME NOT NULL COMMENT '',
  `v_upvote` TINYINT(1) NOT NULL COMMENT '',
  `v_p_post` INT NOT NULL COMMENT '',
  PRIMARY KEY (`v_date`, `v_p_post`)  COMMENT '',
  INDEX `fk_v_votes_p_posts1_idx` (`v_p_post` ASC)  COMMENT '',
  CONSTRAINT `fk_v_votes_p_posts1`
    FOREIGN KEY (`v_p_post`)
    REFERENCES `garlic`.`p_posts` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`csm_connectedsocialmedias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`csm_connectedsocialmedias` ;

CREATE TABLE IF NOT EXISTS `garlic`.`csm_connectedsocialmedias` (
  `csm_sm_name` VARCHAR(20) NOT NULL COMMENT '',
  `csm_u_username` VARCHAR(20) NOT NULL COMMENT '',
  `csm_password` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`csm_sm_name`, `csm_u_username`)  COMMENT '',
  INDEX `fk_sm_socialmedias_has_u_users_u_users1_idx` (`csm_u_username` ASC)  COMMENT '',
  INDEX `fk_sm_socialmedias_has_u_users_sm_socialmedias1_idx` (`csm_sm_name` ASC)  COMMENT '',
  CONSTRAINT `fk_sm_socialmedias_has_u_users_sm_socialmedias1`
    FOREIGN KEY (`csm_sm_name`)
    REFERENCES `garlic`.`sm_socialmedias` (`sm_name`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sm_socialmedias_has_u_users_u_users1`
    FOREIGN KEY (`csm_u_username`)
    REFERENCES `garlic`.`u_users` (`u_username`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`s_subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`s_subscriptions` ;

CREATE TABLE IF NOT EXISTS `garlic`.`s_subscriptions` (
  `s_c_clove` INT NOT NULL COMMENT '',
  `s_u_username` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`s_c_clove`, `s_u_username`)  COMMENT '',
  INDEX `fk_c_clove_has_u_users_u_users1_idx` (`s_u_username` ASC)  COMMENT '',
  INDEX `fk_c_clove_has_u_users_c_clove1_idx` (`s_c_clove` ASC)  COMMENT '',
  CONSTRAINT `fk_c_clove_has_u_users_c_clove1`
    FOREIGN KEY (`s_c_clove`)
    REFERENCES `garlic`.`c_clove` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_c_clove_has_u_users_u_users1`
    FOREIGN KEY (`s_u_username`)
    REFERENCES `garlic`.`u_users` (`u_username`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`ad_admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`ad_admins` ;

CREATE TABLE IF NOT EXISTS `garlic`.`ad_admins` (
  `ad_c_clove` INT NOT NULL COMMENT '',
  `ad_u_username` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`ad_c_clove`, `ad_u_username`)  COMMENT '',
  INDEX `fk_u_users_has_c_clove_c_clove1_idx` (`ad_c_clove` ASC)  COMMENT '',
  INDEX `fk_u_users_has_c_clove_u_users1_idx` (`ad_u_username` ASC)  COMMENT '',
  CONSTRAINT `fk_u_users_has_c_clove_u_users1`
    FOREIGN KEY (`ad_u_username`)
    REFERENCES `garlic`.`u_users` (`u_username`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_u_users_has_c_clove_c_clove1`
    FOREIGN KEY (`ad_c_clove`)
    REFERENCES `garlic`.`c_clove` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
