-- MySQL Script generated by MySQL Workbench
-- 03/14/16 11:56:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema garlic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `garlic` ;

-- -----------------------------------------------------
-- Schema garlic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `garlic` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `garlic` ;

-- -----------------------------------------------------
-- Table `garlic`.`u_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`u_users` ;

CREATE TABLE IF NOT EXISTS `garlic`.`u_users` (
  `u_username` VARCHAR(20) NOT NULL COMMENT '',
  `u_email` VARCHAR(50) NOT NULL COMMENT '',
  `u_password` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`u_username`)  COMMENT '',
  UNIQUE INDEX `u_username_UNIQUE` (`u_username` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`p_posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`p_posts` ;

CREATE TABLE IF NOT EXISTS `garlic`.`p_posts` (
  `p_id` INT NOT NULL COMMENT '',
  `p_content` VARCHAR(10000) NOT NULL COMMENT '',
  `p_date` DATETIME NOT NULL COMMENT '',
  `p_u_username` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`p_id`)  COMMENT '',
  INDEX `fk_p_posts_u_users_idx` (`p_u_username` ASC)  COMMENT '',
  CONSTRAINT `fk_p_posts_u_users`
    FOREIGN KEY (`p_u_username`)
    REFERENCES `garlic`.`u_users` (`u_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`co_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`co_comments` ;

CREATE TABLE IF NOT EXISTS `garlic`.`co_comments` (
  `co_p_id` INT NOT NULL COMMENT '',
  `co_p_commentof` INT NOT NULL COMMENT '',
  PRIMARY KEY (`co_p_id`)  COMMENT '',
  INDEX `fk_co_comments_p_posts2_idx` (`co_p_commentof` ASC)  COMMENT '',
  CONSTRAINT `fk_co_comments_p_posts1`
    FOREIGN KEY (`co_p_id`)
    REFERENCES `garlic`.`p_posts` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_co_comments_p_posts2`
    FOREIGN KEY (`co_p_commentof`)
    REFERENCES `garlic`.`p_posts` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`c_cloves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`c_cloves` ;

CREATE TABLE IF NOT EXISTS `garlic`.`c_cloves` (
  `c_id` INT NOT NULL COMMENT '',
  `c_name` VARCHAR(50) NOT NULL COMMENT '',
  `c_access` TINYINT(1) NOT NULL COMMENT '',
  `c_description` VARCHAR(1000) NULL COMMENT '',
  PRIMARY KEY (`c_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`sm_socialmedias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`sm_socialmedias` ;

CREATE TABLE IF NOT EXISTS `garlic`.`sm_socialmedias` (
  `sm_name` VARCHAR(20) NOT NULL COMMENT '',
  `sm_username` VARCHAR(50) NOT NULL COMMENT '',
  `sm_email` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`sm_name`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`r_rankings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`r_rankings` ;

CREATE TABLE IF NOT EXISTS `garlic`.`r_rankings` (
  `r_rank` INT NOT NULL COMMENT '',
  `r_context` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`r_rank`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`v_votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`v_votes` ;

CREATE TABLE IF NOT EXISTS `garlic`.`v_votes` (
  `v_upvote` TINYINT(1) NOT NULL COMMENT '',
  `v_date` DATETIME NOT NULL COMMENT '',
  `v_p_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`v_date`, `v_p_id`)  COMMENT '',
  INDEX `fk_v_votes_p_posts1_idx` (`v_p_id` ASC)  COMMENT '',
  CONSTRAINT `fk_v_votes_p_posts1`
    FOREIGN KEY (`v_p_id`)
    REFERENCES `garlic`.`p_posts` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`a_articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`a_articles` ;

CREATE TABLE IF NOT EXISTS `garlic`.`a_articles` (
  `a_p_id` INT NOT NULL COMMENT '',
  `a_c_clove` VARCHAR(50) NOT NULL COMMENT '',
  `a_title` VARCHAR(200) NOT NULL COMMENT '',
  `a_r_rank` INT NOT NULL COMMENT '',
  PRIMARY KEY (`a_p_id`, `a_c_clove`, `a_r_rank`)  COMMENT '',
  INDEX `fk_a_articles_c_cloves1_idx` (`a_c_clove` ASC)  COMMENT '',
  INDEX `fk_a_articles_r_rankings1_idx` (`a_r_rank` ASC)  COMMENT '',
  CONSTRAINT `fk_a_articles_p_posts1`
    FOREIGN KEY (`a_p_id`)
    REFERENCES `garlic`.`p_posts` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_a_articles_c_cloves1`
    FOREIGN KEY (`a_c_clove`)
    REFERENCES `garlic`.`c_cloves` (`c_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_a_articles_r_rankings1`
    FOREIGN KEY (`a_r_rank`)
    REFERENCES `garlic`.`r_rankings` (`r_rank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`csm_connectedsocialmedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`csm_connectedsocialmedia` ;

CREATE TABLE IF NOT EXISTS `garlic`.`csm_connectedsocialmedia` (
  `csm_u_username` VARCHAR(20) NOT NULL COMMENT '',
  `csm_sm_name` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`csm_u_username`, `csm_sm_name`)  COMMENT '',
  INDEX `fk_u_users_has_sm_socialmedias_sm_socialmedias1_idx` (`csm_sm_name` ASC)  COMMENT '',
  INDEX `fk_u_users_has_sm_socialmedias_u_users1_idx` (`csm_u_username` ASC)  COMMENT '',
  CONSTRAINT `fk_u_users_has_sm_socialmedias_u_users1`
    FOREIGN KEY (`csm_u_username`)
    REFERENCES `garlic`.`u_users` (`u_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_u_users_has_sm_socialmedias_sm_socialmedias1`
    FOREIGN KEY (`csm_sm_name`)
    REFERENCES `garlic`.`sm_socialmedias` (`sm_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`rc_relatedcloves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`rc_relatedcloves` ;

CREATE TABLE IF NOT EXISTS `garlic`.`rc_relatedcloves` (
  `rc_c_clove1` INT NOT NULL COMMENT '',
  `rc_c_clove2` INT NOT NULL COMMENT '',
  PRIMARY KEY (`rc_c_clove1`, `rc_c_clove2`)  COMMENT '',
  INDEX `fk_c_cloves_has_c_cloves_c_cloves2_idx` (`rc_c_clove2` ASC)  COMMENT '',
  INDEX `fk_c_cloves_has_c_cloves_c_cloves1_idx` (`rc_c_clove1` ASC)  COMMENT '',
  CONSTRAINT `fk_c_cloves_has_c_cloves_c_cloves1`
    FOREIGN KEY (`rc_c_clove1`)
    REFERENCES `garlic`.`c_cloves` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_c_cloves_has_c_cloves_c_cloves2`
    FOREIGN KEY (`rc_c_clove2`)
    REFERENCES `garlic`.`c_cloves` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`ad_admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`ad_admins` ;

CREATE TABLE IF NOT EXISTS `garlic`.`ad_admins` (
  `ad_u_username` VARCHAR(20) NOT NULL COMMENT '',
  `ad_c_clove` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ad_u_username`, `ad_c_clove`)  COMMENT '',
  INDEX `fk_u_users_has_c_cloves_c_cloves2_idx` (`ad_c_clove` ASC)  COMMENT '',
  INDEX `fk_u_users_has_c_cloves_u_users2_idx` (`ad_u_username` ASC)  COMMENT '',
  CONSTRAINT `fk_u_users_has_c_cloves_u_users2`
    FOREIGN KEY (`ad_u_username`)
    REFERENCES `garlic`.`u_users` (`u_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_u_users_has_c_cloves_c_cloves2`
    FOREIGN KEY (`ad_c_clove`)
    REFERENCES `garlic`.`c_cloves` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garlic`.`s_subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garlic`.`s_subscription` ;

CREATE TABLE IF NOT EXISTS `garlic`.`s_subscription` (
  `s_u_username` VARCHAR(20) NOT NULL COMMENT '',
  `s_c_clove` INT NOT NULL COMMENT '',
  PRIMARY KEY (`s_u_username`, `s_c_clove`)  COMMENT '',
  INDEX `fk_u_users_has_c_cloves_c_cloves1_idx` (`s_c_clove` ASC)  COMMENT '',
  INDEX `fk_u_users_has_c_cloves_u_users1_idx` (`s_u_username` ASC)  COMMENT '',
  CONSTRAINT `fk_u_users_has_c_cloves_u_users1`
    FOREIGN KEY (`s_u_username`)
    REFERENCES `garlic`.`u_users` (`u_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_u_users_has_c_cloves_c_cloves1`
    FOREIGN KEY (`s_c_clove`)
    REFERENCES `garlic`.`c_cloves` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
