//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garlic_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_articles
    {
        public string a_title { get; set; }
        public int a_p_post { get; set; }
        public Nullable<int> a_c_clove { get; set; }
        public Nullable<int> a_r_rank { get; set; }
    
        public virtual p_posts p_posts { get; set; }
        public virtual r_rankings r_rankings { get; set; }
    }
}
