//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garlic_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad_admins
    {
        public int ad_c_clove { get; set; }
        public string ad_u_username { get; set; }
    
        public virtual c_cloves c_cloves { get; set; }
    }
}
