//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garlic_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public u_users()
        {
            this.csm_connectedsocialmedias = new HashSet<csm_connectedsocialmedias>();
            this.p_posts = new HashSet<p_posts>();
            this.c_cloves = new HashSet<c_cloves>();
        }
    
        public string u_username { get; set; }
        public string u_email { get; set; }
        public string u_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<csm_connectedsocialmedias> csm_connectedsocialmedias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_posts> p_posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_cloves> c_cloves { get; set; }
    }
}
